Resources:
  DB:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

      AttributeDefinitions:
        - AttributeName: Rollno
          AttributeType: S
          
      KeySchema:
        - AttributeName: Rollno
          KeyType: HASH

      TableName: student-db